/*
 * zhihu_caffe
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// package swagger

package model

type Article struct {

	Id int64 `json:"id,omitempty" gorm:"id;PRIMARY_KEY"`

	Title string `json:"title,omitempty" gorm:"title"`

	ReadNum int64 `json:"readNum,omitempty" gorm:"read_num"`
 
	LikeNum int64 `json:"likeNum,omitempty" gorm:"like_num"`
 
	Content string `json:"content,omitempty" gorm:"content"`
 
	Replies []Reply `json:"replies,omitempty" gorm:"replies"`
 
	Tags []Tag `json:"tags,omitempty" gorm:"tags;many2many:article_tags`
}