/*
 * zhihu_caffe
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"github.com/qt-sc/server/middleware"
	"log"
	"net/http"

	route "github.com/qt-sc/server/route"
)

const PORT string = "8080"

func main() {

	log.Printf("Server started")

	router := route.NewRouter()

	router.Use(middleware.Auth)
	log.Fatal(http.ListenAndServe(":8080", router))

}