/*
 * zhihu_caffe
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	route "github.com/qt-sc/server/route"
)

const PORT string = "8080"

var ZHIHU_URL string = "http://news-at.zhihu.com/api/4/news"
var LA string = "/latest"

func main() {

	log.Printf("Server started")

	router := route.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))

}