/*
 * zhihu_caffe
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// package swagger

package service

import (
	"encoding/json"
	"github.com/qt-sc/server/lib"
	"log"
	"net/http"
	"strconv"
)

func GetArticles(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)

	url := r.RequestURI
	idstr := lib.GetFollowParameter(url, "users")
	id, err := strconv.Atoi(idstr)
	if err != nil {
		log.Fatal("string to int fail", err)
	}
	articles, err := dbServer.GetArticleByUser(id)
	if err != nil {
		log.Fatal("Fail to get article by ID", err)
	}

	msg, err := json.Marshal(articles)
	if err != nil {
		log.Fatal("JSON Marshal fail.", err)
	}
	w.Write(msg)
}

func GetArticle(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)

	url := r.RequestURI
	idstr := lib.GetFollowParameter(url, "users")
	id, err := strconv.Atoi(idstr)
	if err != nil {
		log.Fatal("string to int fail", err)
	}
	articles, err := dbServer.GetArticleByArticle(id)
	if err != nil {
		log.Fatal("Fail to get article by ID", err)
	}

	msg, err := json.Marshal(articles)
	if err != nil {
		log.Fatal("JSON Marshal fail.", err)
	}
	w.Write(msg)
}

func PostArticle(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
