/*
 * zhihu_caffe
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
// package swagger

package service

import (
	"encoding/json"
	"log"
	"net/http"
)

func GetArticles(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)

	err := r.ParseForm()
	if err != nil {
		log.Fatal("parse form error", err)
	}
	var formData int
	err = json.NewDecoder(r.Body).Decode(&formData)
	if err != nil {
		log.Fatal("decode error", err)
	}

	articles, err := dbServer.GetArticles(formData)
	if err != nil {
		log.Fatal("Fail to get article by ID", err)
	}

	msg, err := json.Marshal(articles)
	if err != nil {
		log.Fatal("JSON Marshal fail.", err)
	}
	w.Write(msg)
}

func GetArticle(w http.ResponseWriter, r *http.Request) {

}

func PostArticle(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}